#!/usr/bin/env bash

dev=""
mountpoint="/home/qeni/mnt"

main()
{
    echo "Your device is [sdb1]: \n> /dev/" 
    read dev
    if [[ "$dev" == "" ]]; then
        dev="sdb1"
    fi

    cecho g "=========================> Is it ntfs? [Y/n]: "
    read is_ntfs
    if [[ "$is_ntfs" == "n" || "$is_ntfs" == "N" ]]; then
        sudo mount /dev/$dev "$mountpoint"
    else
        sudo ntfs-3g /dev/$dev "$mountpoint"
    fi
}

main
