#!/usr/bin/env bash

dev=""
mountpoint="/home/qeni/mnt"

cecho() {
  local code="\033["
  case "$1" in
    black  | bk) color="${code}0;30m";;
    red    |  r) color="${code}1;31m";;
    green  |  g) color="${code}1;32m";; yellow |  y) color="${code}1;33m";; blue   |  b) color="${code}1;34m";;
    purple |  p) color="${code}1;35m";;
    cyan   |  c) color="${code}1;36m";;
    gray   | gr) color="${code}0;37m";;
    *) local text="$1"
  esac
  [ -z "$text" ] && local text="$color$2${code}0m"
  printf "$text"
}

main()
{
    cecho g "=========================> Type your dev:\n"
    cecho g "Your device is [sdb1]: \n> /dev/" 
    read dev
    if [[ "$dev" == "" ]]; then
        dev="sdb1"
    fi

    status2=$?

    cecho g "=========================> Is it ntfs? [Y/n]:\n"
    cecho g "> " 
    read is_ntfs
    if [[ "$is_ntfs" == "n" || "$is_ntfs" == "N" ]]; then
        sudo mount /dev/$dev "$mountpoint"
    else
        sudo ntfs-3g /dev/$dev "$mountpoint"
    fi

    status2=$?

    cecho r "=========================> Done\n"
}

main
